{% set name = "monty" %}
{% set version = "1.0.2" %}
{% set sha256 = "02aa70d1c31ac19890817ceb39dac08909d7595ea96b7b0179a1f113ebdaabfc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - monty
    - monty.os

about:
  home: https://github.com/materialsvirtuallab/monty
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Monty is the missing complement to Python.'
  description: |
    Monty is the missing complement to Python. Monty implements supplementary useful functions
    for Python that are not part of the standard library. Examples include useful utilities like
    transparent support for zipped files, useful design patterns such as singleton and cached_class, 
    and many more.
  doc_url: https://materialsvirtuallab.github.io/monty/
  dev_url: https://github.com/materialsvirtuallab/monty

extra:
  recipe-maintainers:
    - shyuep
