{% set name = "monty" %}
{% set version = "2025.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/monty-{{ version }}.tar.gz
  sha256: 16c1eb54b2372e765c2f3f14cff01cc76ab55c3cc12b27d49962fb8072310ae0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - numpy
    - ruamel.yaml
    - python >={{ python_min }}

test:
  imports:
    - monty
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsvirtuallab/monty
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Monty is the missing complement to Python.
  description: |
    Monty is the missing complement to Python. Monty implements supplementary useful functions
    for Python that are not part of the standard library. Examples include useful utilities like
    transparent support for zipped files, useful design patterns such as singleton and cached_class, 
    and many more.
  doc_url: https://materialsvirtuallab.github.io/monty/
  dev_url: https://github.com/materialsvirtuallab/monty

extra:
  recipe-maintainers:
    - shyuep
    - jan-janssen
